NVIDIA/nv-ingest

helm/README.md
Adds a suggested Minikube configuration to prevent permission issues when using the Helm chart
=> Add minikube instructions for PVC storage

src/nv_ingest/modules/transforms/embed_extractions.py
This PR resolves #60 by handling cases where embedding tasks flags are all set to false and/or no extracted content is a candidate for embedding.
=> Embedding module bug fix resolves #60

src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py
This changes the confidence threshold and adds a final threshold in pdfium's table extraction helper function to fix an issue with chart bounding boxes
=> Fix chart bbox issue

README.md, client/src/nv_ingest_client/client/client.py
The default NvIngestClient has been updated to use the `RestClient` instead of the `RedisClient` in the init method there was a place missed which still defaulted to the old port 6379 which was for Redis and was not updated to the new HTTP port of 7670. This PR addresses that and removes a few other mentions of Redis that were noticed in the docstrings.
=> Update NvIngestClient default port

helm/README.md, skaffold/README.md
Update the Helm documentation with a note about accessing the services running on Helm with the nv-ingest-cli or python library
=> Adjust helm docs to note interacting with Helm assets is possible

.github/workflows/docker-build.yml
I noticed [some warnings on our new CI actions](https://github.com/NVIDIA/nv-ingest/actions/runs/11001410068) and am making a small PR to bump our versions which should remove the warnings and make sure we're on a supported version.
=> Update action versions

README.md
Adds a note set NVIDIA as default container runtime before running docker compose. Closes #101
=> Add note to set NVIDIA as default container runtime

client/src/nv_ingest_client/message_clients/rest/rest_client.py, tests/nv_ingest_client/client/test_rest_client.py
Handles if a HTTP/S is pre-pended to the user provided URL. If it is the value is kept as is assuming the user knows what they are doing and would like to override the default behavior. If it is not then the URL is pre-pended with the default `http://` value.
This closes: #103
=> Handle the existance of HTTP/S pre-pended to the Rest server URL

src/nv_ingest/extraction_workflows/pptx/pptx_helper.py, tests/nv_ingest/extraction_workflows/pptx/test_pptx_helper.py
Fixes a bug where 1. If there are multiple runs in a title or a subtitle, the title/subtitle will be counted multiple times, and 2. there were too many newline characters to delimit the slides/paragraphs/runs. The logic related to whitespaces is moved around to have the existing unit tests pass, and new unit tests are added to test these cases.
=> Support multiple runs in title and delimiter fix for pptx

.github/workflows/docker-build.yml, .github/workflows/docker-nightly-publish.yml
Configure the Github action to build the --target runtime so that all components needed for running are available by default.
=> Build runtime docker target instead of development

Dockerfile
Bump the Python version from 3.10.14 -> 3.10.15. The Morpheus base container currently ships with 3.10.14 so we perform that manual conda installation step in the Dockerfile.
This closes: #104
=> Bump Python version 3.10.14 -> 3.10.15

README.md, client/src/nv_ingest_client/nv_ingest_cli.py, client/src/nv_ingest_client/primitives/tasks/extract.py, src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py, tests/nv_ingest_client/primitives/tasks/test_extract.py
This PR introduces an optional `extract_charts` parameter to both the CLI and Python client. When `extract_charts` is set to false, the process will skip the deplot and cached steps. If the parameter is not specified, the default behavior remains unchanged, ensuring backward compatibility by continuing to run both table and chart extraction as before.
=> Add extract_charts option for disabling chart extraction

src/nv_ingest/stages/multiprocessing_stage.py
This PR is a bug fix, following up on https://github.com/NVIDIA/nv-ingest/pull/109, where the return value of `process_fn` was unpacked. It was an attempt at having the PDF extraction functions return a tuple of `(extracted_data, {"trace_info": trace_info}` and making it compatible with other extration functions (pptx, docx, etc.) which does not return the `trace_info`. This PR adds an extra check to ensure that the return value is unpackable. Without this check, since `extracted_data` is a data frame, the data frame will be unpacked.
=> Check if return value of extractor functions is unpackable

docker-compose.yaml, src/nv_ingest/api/main.py, src/nv_ingest/api/v1/health.py, src/nv_ingest/api/v1/ingest.py, src/nv_ingest/main.py, src/nv_ingest/util/nim/helpers.py
nv-ingest as a service should offer a "readiness" endpoint that both signals to end users or container orchestration technologies like k8s it is in a ready state for processing.
Since nv-ingest (in the service context) is comprised of several components this `/v1/health/ready` endpoint will reach out to all of those components via their "ready" endpoints and then aggregate the results. Once ALL of the configured components are ready nv-ingest will report that it is ready as well.
Ready = HTTP 200
Not Ready = HTTP 503  as well as a JSON payload describing the individual components that are ready or not ready.
=> Add /v1/health/ready "ready" endpoint for nv-ingest

Dockerfile, client/src/nv_ingest_client/cli/util/processing.py, docker-compose.yaml, src/nv_ingest/modules/sinks/redis_task_sink.py, src/pipeline.py
Resolves #155 
Adds:
- MRC_IGNORE_NUMA_CHECK env variable -- bypasses situations where GPUs are assigned to more than one NUMA node.  Which previously would cause MRC's NumaPlacement strategy to fail.
- Updates redis_task_sink to conver mdf to pandas before calling to_dict -- A bit hand-wavey on this, converting to Pandas works and the 'unexpected keyword value 'index'' error that comes out of cuDF is outside our control.
=> Various compatitbility fixes for pyarrow 17 and cuda 12.2

client/src/nv_ingest_client/nv_ingest_cli.py
Add missing docstring for 'text_depth' extraction option.
=> Documentation fix for 'extract_task'

src/nv_ingest/modules/sinks/redis_task_sink.py
Fixes
```
nv-ingest-ms-runtime-1  | E20241015 00:55:19.766779 132771194340928 context.cpp:124] /main/mrc::pymrc::PythonSegmentModule::redis_task_sink/process_and_forward; rank: 5; size: 6; tid: 132771
194340928: set_exception issued; issuing kill to current runnable. Exception msg: ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()
```
=> Fix dataframe emptiness check

src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py
Fixes
```
nv-ingest-ms-runtime-1  | 2024-10-16 21:31:52,923 - ERROR - Error during table/chart extraction: local variable 'paddle_version' referenced before assignment
nv-ingest-ms-runtime-1  | 2024-10-16 21:31:52,926 - ERROR - Future result failure - local variable 'paddle_version' referenced before assignment
nv-ingest-ms-runtime-1  |
nv-ingest-ms-runtime-1  | Unhandled exception in decode_and_extract for './data/multimodal_test.pdf':
nv-ingest-ms-runtime-1  | local variable 'paddle_version' referenced before assignment
nv-ingest-ms-runtime-1  | Unhandled exception in process_pdf_bytes: local variable 'paddle_version' referenced before assignment
```
=> Fix paddle version missing when extract_tables is false

Dockerfile
Installs curl for [healthcheck](https://github.com/NVIDIA/nv-ingest/blob/main/docker-compose.yaml#L161).
```
$ docker ps
CONTAINER ID   IMAGE                                                                      COMMAND                  CREATED          STATUS                      PORTS                                                                                                                                                                                                                                                                                NAMES
d0d78f932ffe   nvcr.io/ohlfw0olaadg/ea-participants/nv-ingest:24.08                       "/opt/conda/envs/nv_…"   38 seconds ago   Up 38 seconds (healthy)     0.0.0.0:7670->7670/tcp, :::7670->7670/tcp …
```
=> Install curl for healthcheck

helm/values.yaml, src/nv_ingest/api/main.py
Adjusted Helm values.yaml parameters for NIM http endpoints and http check endpoints.
=> Adjust NIM endpoint inference endpoints, and adding http endpoints

helm/values.yaml
Increase the requested memory to 6Gi and the limit memory to 12Gi for both Redis Master and Replicas
=> Increase Redis master and replica memory for k8s

src/nv_ingest/modules/sinks/redis_task_sink.py
Resolves #187 
Updates the logic that creates and validates multi-part fragment sizes returned to the user. Here we just set the fragment size to 128 MB, and the maximum fragment size to 256 MB so there is a buffer.
- [x New or existing tests cover these changes.
=> Resolve issue 187

src/nv_ingest/util/nim/decorators.py, src/nv_ingest/util/nim/helpers.py, tests/nv_ingest/util/nim/test_decorators.py
This PR adds a caching mechanism to the http call to /v1/metadata (which gives us version info). A simple approach such as `functools.lru_cache` is not effective because these http calls are currently used in the extractor stage and extractor stages are multiprocessing stages. To prevent overladoing workers with highly concurrent requests, we introduce a cache that is invalidated after n calls, where the total call count is shared across multiple processes.
=> Cache nim version metadata calls and invalidate periodically

docker-compose.yaml
Default docker compose back to local deplot deployment.
=> Fix docker compose changes

tests/nv_ingest/modules/filters/test_image_dedup.py, tests/nv_ingest/modules/filters/test_image_filter.py, tests/nv_ingest/modules/storages/test_image_storage.py, tests/nv_ingest/modules/telemetry/test_otel_tracer.py, tests/nv_ingest/modules/transforms/test_associate_nearby_text.py, tests/nv_ingest/util/converters/test_dftools.py
Update various unit tests to skip if CUDA is not available.
=> Update various unit tests to skip if CUDA is not available.

Dockerfile
Bump the base container for nv-ingest to cuda 12.4.1
=> Bump to cuda 12.4.1 base image

client/client_examples/examples/python_client_usage.ipynb
Add the split task to the job in the client example notebook (to prevent confusion).
=> Add Split Task to Job in Client Demo

client/requirements.txt
If you follow the instructions in the main README of doing
```
conda create --name nv-ingest-dev python=3.10
conda activate nv-ingest-dev
cd client
pip install -r ./requirements.txt
pip install .
```
Then if you run the notebook examples in:
```
client/client_examples/examples/python_client_usage.ipynb
```
you'll get an Import Error saying that the `fsspec` is required. A simple pip install of the library fixes the issue and hence I've added it to the requirements.txt file.
=> Add missing requirements for Python client

README.md
Currently in the README, the recommended way to run `docker compose` is:
```
docker compose up
```
this means that the command will use an already published container, rather than building from source. 
I've add a tip to use:
```
docker compose up --build
```
Since sometimes the published containers might have bugs that have only been fixed in the `main` branch and hence users would benefit from being "reminded" to build from source.
=> Add tip to run `docker compose up --build` to build from source into README

src/nv_ingest/modules/transforms/embed_extractions.py, src/nv_ingest/stages/nim/chart_extraction.py, src/nv_ingest/stages/nim/table_extraction.py
Some documents have nothing to extract. This PR proposes to skip extraction stages if there is no data in the dataframes.
=> Skip extractions if there is nothing to extract

docker-compose.yaml
=> Revert docker-compose to default to using Redis as its message broker

client/requirements.txt, client/src/nv_ingest_client/util/milvus.py
This PR fixes the requirements to support the use of the milvus tools. It also creates another layer of abstraction to make it easier to create a nv-ingest collection, write records to that collection and search against those records. Supports both hybrid and dense search.
=> add requirements and final abstraction

Dockerfile, setup.py
Drops us from 20.4 GB to 17 GB
=> Add conda cache cleanup to dockerfile to reduce final image size

client/src/nv_ingest_client/client/client.py, client/src/nv_ingest_client/util/processing.py
The profiling PR https://github.com/NVIDIA/nv-ingest/pull/251 introduced a bug where a call to `handle_future_result` was not properly unpacking the resulting Tuple causing issues.
=> Adjust all calls to handle_future_result to unpack result and trace_id

client/src/nv_ingest_client/cli/util/click.py, tests/nv_ingest_client/cli/util/test_click.py
Tasks should be combined with `task_id`. This bug didn't get noticed because two unit tests shared the same name, and the second test overwrote the first one.
=> Fix task_id and task tuple bug in client

client/requirements.txt, client/src/nv_ingest_client/util/milvus.py
This PR adds support for milvus lite, it checks for the version of milvus and if you are using the embedded version, ensures you use the correct index params (no GPU CAGRA) and it uses streaming insert. Also added output_fields as a param for searches. Pinned versions of packages to ensure pypi only downloads one version of each package instead of download all of them.
=> add streaming milvus capability, output_fields param, and pin pacakges

src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py, src/nv_ingest/stages/nim/chart_extraction.py, src/nv_ingest/stages/nim/table_extraction.py, src/nv_ingest/util/nim/helpers.py, src/nv_ingest/util/tracing/tagging.py, tests/nv_ingest/stages/nims/test_chart_extraction.py, tests/nv_ingest/stages/nims/test_table_extraction.py
Tracing mechanism from #109 was lost during a recent refactor. This PR retores the finer-grained traces at the NIM level (`yolox_0`, ..., `paddle_0`, ..., `deplot_0`, ... below).
=> enable traces for yolox, cached, and deplot

Dockerfile
Add caching for conda packages to Dockerfile to speed up successive builds.
=> Add caching for conda packages to Dockerfile to speed up successive builds.

config/otel-collector-config.yaml
Add the `http.endpoint` entry in the `receivers` section of the `config/otel-collector-config.yaml` configuration file. The `http` entry is needed by the `yolox` service. This PR closes #297
=> Add missing receivers configuration for http protocol

helm/templates/service.yaml
Adjust helm spec.ports[1].name from `http` -> `nv-ingest-http` which was conflicting with other NIM services and causing deployment issues.
=> Adjust spec.ports[1].name to nv-ingest-http from http

src/nv_ingest/util/pipeline/stage_builders.py
This PR proposes to use the build api key when we use the build api endpoints in embedding extraction, similarly to image NIMs.
=> Use build api key as backup in embedding extraction

.github/workflows/conda-nightly-publish.yml, .gitignore, conda/build_conda_packages.sh
Introduces a new Github action that builds the `nv-ingest` and `nv-ingest-client` anaconda packages and publishes them to the Nvidia Anaconda repo as nightly packages.
=> Github Action to build and publish nightly nv-ingest Conda packages

docs/docs/user-guide/developer-guide/kubernetes-dev.md
Fix some broken links and light editing in kubernetes.md
=> Fix some broken links and light editing in kubernetes.md

.github/workflows/build-docs.yml, .gitignore
Builds the nv-ingest documentation site on each merge to main and nightly. This PR currently does not physically push the site anywhere as we have yet to determine that location. A future PR will handle the actual publishing of the site.
=> Build nv-ingest docs with CI

conda/packages/nv_ingest/build.sh, conda/packages/nv_ingest/meta.yaml, conda/packages/nv_ingest_client/build.sh, conda/packages/nv_ingest_client/meta.yaml
Add build.sh scripts and have them export the date_string environment variable for the conda meta.yaml to use.
=> Adjust build.sh script to export DATE_STRING

conda/build_conda_packages.sh
Update the conda build script to pass along the DATE_STRING for the conda meta packaging to use.
=> Update conda build script to include date

client/src/nv_ingest_client/util/milvus.py
this PR reverts the logic that allows for indexing on GPU and search on CPU. Current settings degrade recall drastically.
=> reverting adapt cpu logic to use GPU as default

src/nv_ingest/modules/transforms/embed_extractions.py
Embedding NIM services return errors if the input text is empty or all whitespace. This PR updates the content filtering logic to ensure strings with only whitespace are excluded from the embedding process.
=> Filter out whitespace-only strings before embedding

api/LICENSE, api/README.md, api/pyproject.toml, conda/build_conda_packages.sh, conda/environments/nv_ingest_api_environment.yml, conda/packages/nv_ingest_api/meta.yaml, conda/packages/nv_ingest_client/meta.yaml, pytest.ini
Introduce the `nv-ingest-api` package which will serve as the home for purely pythonic code from nv-ingest that is meant to be shared across several modules and runtimes.
This PR simply sets up the directory structure, conda build, and CI for building the package and deploying the nightly.
This package is currently empty on purpose as components will slowly be moved over to it from other locations.
=> introduce nv-ingest-api package

client/src/nv_ingest_client/util/milvus.py, docker-compose.yaml
updates the milvus container and adds support for continuous update on bm25 while adding new data points when using container. Still allows Embedding functionality previously available when using milvus-lite.
=> adds 2.5.3 bm25 support while keeping previous support for milvus lite

.pre-commit-config.yaml
This PR adjusts the pre-commit hooks to ignore the `docs/` directory for the `trailing-whitespace` hook.
I would recommend uninstalling, cleaning, and reinstall your local pre-commit hooks to validate this works.
```bash
pre-commit uninstall
pre-commit clean
pre-commit install
```
=> Adjust trailing-whitespace hook to ignore the docs/ directory

client/src/nv_ingest_client/util/milvus.py
Adds logging for any time an element is processed and does not have an embedding or text (charts, tables, text, images)
=> add error check for embedding and text with logging

src/nv_ingest/stages/multiprocessing_stage.py, src/nv_ingest/stages/nim/table_extraction.py, src/nv_ingest/util/nim/cached.py, src/nv_ingest/util/nim/helpers.py, src/nv_ingest/util/nim/paddle.py, tests/nv_ingest/util/nim/test_helpers.py, tests/nv_ingest/util/nim/test_paddle.py
This PR addresses a race condition found in the pseudo markdown method's used by the paddleOCR wrapper, improves error descriptions coming out of the NimClient, and correctly raises errors in the table_extraction stage where they were previously ignored.
Some minor function docs updates as well.
=> Correctly raise errors in table-extract and fix race condition in paddle markdown generation

skaffold/README.md
Fix a broken link from the Skaffold readme page to a doc page.
Closes #322
=> Fix a broken link from the Skaffold readme page to a doc page

src/nv_ingest/extraction_workflows/image/image_handlers.py, src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py, src/nv_ingest/stages/nim/chart_extraction.py, src/nv_ingest/stages/nim/table_extraction.py, src/nv_ingest/util/nim/cached.py, src/nv_ingest/util/nim/deplot.py, src/nv_ingest/util/nim/helpers.py, src/nv_ingest/util/nim/paddle.py, src/nv_ingest/util/nim/yolox.py, tests/nv_ingest/stages/nims/test_chart_extraction.py, tests/nv_ingest/stages/nims/test_table_extraction.py, tests/nv_ingest/util/nim/test_cached.py, tests/nv_ingest/util/nim/test_deplot.py, tests/nv_ingest/util/nim/test_helpers.py, tests/nv_ingest/util/nim/test_paddle.py, tests/nv_ingest/util/nim/test_yolox.py
Changes:
- Begins to shift batching responsibility to NimClient and ModelInterface abstractions
- Attempts to detect max batch size from the NIM if gRPC endpoint is available (HTTP API does not yet support)
- Defaults to batch size 1 if we can't detect the true batch size, but allows the caller to override.
=> Incremental shift towards dynamic batching

client/src/nv_ingest_client/util/milvus.py
This PR adds the bounding boxes of images/tables/charts to the metadata stored on milvus. To avoid inflating the milvus usage unnecessarily, we only extract the necessary bounding box values and insert them into the existing `content_metadata` field.
=> add bounding box to content metadata on milvus

client/requirements.txt, examples/langchain_multimodal_rag.ipynb
Pin to langchain-nvidia-ai-endpoints >= 0.3.7 to allow for "prepended model names" to be used for custom model invocation.
=> Pin to langchain-nvidia-ai-endpoints >= 0.3.7

.github/workflows/pypi-nightly-publish.yml, client/setup.py
Builds the python wheel for `nv-ingest-client` and publishes that wheel to the upstream artifactory repository.
=> Github Action: Build nv-ingest-client wheel and publish to artifactory

README.md, docs/docs/user-guide/developer-guide/environment-config.md, docs/docs/user-guide/getting-started/quickstart-guide.md
- Fix broken links x2
- Table-fy environment variables: even though the environment variables page looks okay in the GitHub build, in the [docs.nvidia.com Environment page](https://docs.nvidia.com/nv-ingest/user-guide/developer-guide/environment-config/) build, it looks terrible.
=> Fix broken links, table-fy environment variables

src/nv_ingest/extraction_workflows/image/image_handlers.py, src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py, src/nv_ingest/stages/nim/chart_extraction.py, src/nv_ingest/stages/nim/table_extraction.py, src/nv_ingest/util/nim/helpers.py, src/nv_ingest/util/nim/yolox.py, src/nv_ingest/util/pdf/pdfium.py, tests/nv_ingest/stages/nims/test_chart_extraction.py, tests/nv_ingest/stages/nims/test_table_extraction.py
Removes batching/concurrency responsibility from individual stages, and lets the NimClient decide (with the option to override)
=> Consolidate batching and concurrency decisions to the NimClient

.github/workflows/docker-build.yml, .github/workflows/docker-nightly-publish.yml, .github/workflows/docker-release-publish.yml, Dockerfile
Embeds the `git rev-parse HEAD` output as metadata in the Docker container labels. This makes it much easier for people to trace each container back to the git commit that was associated with it.
The data MUST be passed to the docker build command for this to work. Like so with the --build-arg "GIT_COMMIT"
```
docker build --target runtime --build-arg GIT_COMMIT=$(git rev-parse HEAD) -t nv-ingest:latest .
```
Docker containers can then be examine to view the git commit associated with them by running something like ....
```
docker inspect nv-ingest:latest | jq '.[0].Config.Labels.git_commit'
```
=> Embed git rev-parse in docker metadata labels

client/src/nv_ingest_client/util/milvus.py
This fixes a bug where the ClientConfigSchema was not instantiated before reference. We want to instantiate so that we can pick up any changes to environment variables that happen before calling this function. See test cases in `tests/nv_ingest_client/util/test_util.py`
=> instantiate client config schema

README.md
The command as documented gives this error:
```
$ conda create --name nv-ingest-dev --file ./conda/environments/nv_ingest_environment.yml
conda activate nv-ingest-dev
CondaValueError: could not parse 'name: nv_ingest_runtime' in: ./conda/environments/nv_ingest_environment.yml
EnvironmentNameNotFound: Could not find conda environment: nv-ingest-dev
You can list all discoverable environments with `conda info --envs`.
```
=> Fix conda create command

client/src/version.py
Fixes errors like:
```
WARNING: Built wheel for nv-ingest-client is invalid: Wheel has unexpected file name: expected '2025.2.13.dev20250213110023', got '2025.2.13.dev20250213110039'
Failed to build nv-ingest-client
ERROR: Failed to build installable wheels for some pyproject.toml based projects (nv-ingest-client)
```
=> Remove time from the revision string

client/client_examples/examples/python_client_usage.ipynb, client/src/nv_ingest_client/util/milvus.py
The example notebook does not mention the `dense_dim` parameter and because of the default parameter passed to MilvusOperator is 1024, this means that new embedding models like Llama 3.2 which have embedding dimensions 2048 do not work. For user-friendliness and clarity, it's best to leave the parameter in the notebook example
=> add dense_dim parameter to client notebook and change default param on MilvusOperator

client/setup.py, conda/packages/nv_ingest_client/meta.yaml
Conda builds should be using the pyproject.toml built in setuptools plugin. For whatever reason that plugin is currently failing and general knowledge seems to be just add an empty setup.py file to pacify the broken plugin piece until a fix is made.
=> Add empty setup.py file to pacify conda wanting a setup.py file

client/src/nv_ingest_client/util/milvus.py
This PR adds bounding box information in streaming mode to mirror the bulk upload mode:
https://github.com/NVIDIA/nv-ingest/blob/e1802b25eabd873fb6c6c45ebbf7724faaf87df6/client/src/nv_ingest_client/util/milvus.py#L438-L441
=> add bounding box to milvus metadata in streaming mode

.github/workflows/build-docs.yml
Update CI container to ubuntu:latest for docs so that build utilities are present by default. This makes more sense than trying to manually install them on python:slim
=> Change docs ci container to ubuntu latest to ensure make is present

.github/workflows/build-docs.yml
Install Python3 and pip on the ubuntu latest image since they are not present at CI runtime.
=> Install python3 and pip with symlink on ubuntu latest image

.github/workflows/build-docs.yml, helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
This PR add the `nvidia-nim-llama-32-nv-embedqa-1b-v2` NIM to the Helm chart in favor of the previous `nv-embedqa-e5-v5` NIM.
`nv-embedqa-e5-v5` is still left in the chart but is disabled by default. Both of these NIMs deploy under the same fullname of `nv-ingest-embedqa`.
If you would prefer to continue using the `nv-ingest-embedqa` NIM you can add these `--set` commands to your helm command to deploy `nv-ingest-embedqa`
Note:
embedqaDeployed = `nv-embedqa-e5-v5`
nvEmbedqaDeployed = `nvidia-nim-llama-32-nv-embedqa-1b-v2`
Note:
Both values cannot be set to true
```bash
--set embedqaDeployed=true \
--set nvEmbedqaDeployed=false
```
Apologies for the confusing names but they were inherited.
=> Add nvidia-nim-llama-32-nv-embedqa-1b-v2 to Helm chart

.github/workflows/build-docs.yml, docs/requirements.txt, docs/sphinx_docs/Makefile, docs/sphinx_docs/source/conf.py
Change docs CI build container to python:3.11-slim from ubuntu:latest
=> Docs CI build changes

client/src/nv_ingest_client/util/milvus.py
PR moves the sleep for 20 seconds to only happen when bulk ingestion is used. This gives milvus the required administration setup time to get ready to handle retrieval calls on the recently created index.
=> move sleep to only run when using bulk ingestion for milvus

client/src/nv_ingest_client/client/interface.py
This PR fixes a bug with the ingest_async call that I introduced in a previous PR when passing records to milvus. Before you only grabbed the first document, this change fixes this so that all documents are ingested by milvus.
=> fix to get all records from results in ingest_async for milvus

client/src/nv_ingest_client/client/interface.py, tests/nv_ingest_client/client/test_interface.py
This PR ensures that users get the same results format whether using ingest or ingest_async.
=> match results from ingest and ingest-async

.github/workflows/build-docs.yml, Dockerfile
Use the full nv-ingest container for building the api docs. This is needed due to sphinx autodoc needed the dependencies installed for our template.
=> Use full container for generating api docs

client/src/nv_ingest_client/client/interface.py, tests/nv_ingest_client/client/test_interface.py
This PR reverts previous change, so that ingest_async returns the future instead of the results
=> async results reverted to future

src/nv_ingest/modules/transforms/text_splitter.py
This fixes a bug that causes the Split task to drop the last token
=> Fix bug causing last token in text splits to get dropped

src/nv_ingest/stages/embeddings/text_embeddings.py
This PR updates the content filtering logic to ensure null content fields are excluded from the embedding process.
=> filter out null content before embedding

src/nv_ingest/extraction_workflows/image/image_handlers.py
This update modifies `extract_page_elements_from_images` to dynamically retrieve the YOLOX model name using `get_yolox_model_name` based on the configured HTTP endpoint. The model name is then passed to `YoloxPageElementsModelInterface`, ensuring the correct version is used for inference. This change applies to image, docx, and pptx extraction paths
=> set yolox modle name dynamically for image, docx, and pptx paths

docker-compose.yaml
Adjust the docker-compose.yaml `user` argument for otel-collector to avoid permissions issues with the otel config file in certain situations inside the container.
=> Adjust otel-collector docker-compose user argument

client/src/nv_ingest_client/util/milvus.py, tests/nv_ingest_client/util/test_milvus_util.py
This PR allows a user to reconstruct the full page that belongs to a retrieved chunk. It can also pull surrounding pages based on user page_signum input.
=> Page reconstruction

client/src/nv_ingest_client/util/milvus.py
This PR fixes an issue with collections when you restart milvus, they seem to have some metadata attached that associates the collections with the instance of milvus that created them. So even though you have the index parameters and the same schema if you try to use the create collection api it will still say that you are trying to create a collection with a different set of parameters, instead of returning the already existing collection. This PR gives us the desired behavior where it uses the supplied collection. Now we no longer create a collection if the collection already exists (when recreate is false).
=> no create when already exists

client/src/nv_ingest_client/primitives/jobs/job_spec.py, client/src/nv_ingest_client/primitives/tasks/__init__.py
Updated `add_task` in `JobSpec` to check `task._extract_method` instead of `_DEFAULT_EXTRACTOR_MAP[self._document_type]` when determining if an `AudioExtractionTask` should be added. This improves encapsulation by relying on task properties rather than an external mapping.
=> Use extract method to add add audio extraction task

src/nv_ingest/util/pipeline/stage_builders.py
This PR removes the incorrectly overridden task type `task="extract"` (task should be `audio_data_extract` not extract) in the audio extraction builder. By removing, this stage will use the default value `audio_data_extract` in
https://github.com/NVIDIA/nv-ingest/blob/14a859f2e825a7c7442874523e1817a1af533077/src/nv_ingest/stages/nim/audio_extraction.py#L158-L159
=> use default task and task properties in audio extraction stage

client/src/nv_ingest_client/primitives/tasks/embed.py, src/nv_ingest/modules/transforms/embed_extractions.py, src/nv_ingest/schemas/ingest_job_schema.py, src/nv_ingest/stages/embeddings/text_embeddings.py, tests/nv_ingest_client/primitives/tasks/test_embed.py
This introduces the `EMBEDDING_NIM_ENDPOINT` env variable to the client which will default to https://integrate.api.nvidia.com/v1 if unset or empty string, and will convert urls that don’t start with http:// or https:// to the format `http://<EMBEDDING_NIM_ENDPOINT>/v1`
=> Add embedding nim endpoint and model name env variables to client

src/nv_ingest/util/pdf/pdfium.py
Avoid literal constants, and use the variables from the bindings instead.
Also, avoid a needless call of bitmap.get_info() (will disappear in v5). Instead, take the .mode from the bitmap object directly.
Disclaimer: untested.
This is a re-submission of https://github.com/NVIDIA/nv-ingest/pull/412 with signed-off commit.
- New or existing tests cover these changes.
- The documentation is up to date with these changes.
- If adjusting docker-compose.yaml environment variables have you ensured those are mimicked in the Helm values.yaml file.
=> pdfium: use the variables rather than literal constants (signed-off variant)

client/src/nv_ingest_client/primitives/tasks/embed.py, src/nv_ingest/modules/transforms/embed_extractions.py, src/nv_ingest/schemas/ingest_job_schema.py, src/nv_ingest/stages/embeddings/text_embeddings.py, tests/nv_ingest_client/primitives/tasks/test_embed.py
Reverts env variable logic changes from #440 and adds endpoint_url, model_name, and api arguments to `.embed()`
=> Revert embedding env variable changes

client/src/nv_ingest_client/nv_ingest_cli.py, helm/values.yaml, src/nv_ingest/schemas/image_caption_extraction_schema.py, src/nv_ingest/util/pipeline/pipeline_runners.py, src/nv_ingest/util/pipeline/stage_builders.py, tests/nv_ingest/schemas/test_image_caption_extraction_schema.py
Change default VLM endpoints from 90b -> 11b
=> Adjust default vlm endpoints

src/nv_ingest/util/pipeline/pipeline_runners.py
Since the schema field names are used for overwriting the environment variables:
https://github.com/NVIDIA/nv-ingest/blob/6eed5f77d1400a87080fa0e6f7580be580c2c0e6/src/nv_ingest/util/pipeline/pipeline_runners.py#L389-L390
they should match the environment variable names, e.g.,
https://github.com/NVIDIA/nv-ingest/blob/6eed5f77d1400a87080fa0e6f7580be580c2c0e6/docker-compose.yaml#L287
=> Rename  field names for library mode

client/src/nv_ingest_client/primitives/jobs/job_spec.py, client/src/nv_ingest_client/primitives/tasks/audio_extraction.py, client/src/nv_ingest_client/util/process_json_files.py, src/nv_ingest/schemas/audio_extractor_schema.py, src/nv_ingest/schemas/ingest_job_schema.py, src/nv_ingest/stages/nim/audio_extraction.py, src/nv_ingest/util/nim/parakeet.py, src/nv_ingest/util/pipeline/pipeline_runners.py, src/nv_ingest/util/pipeline/stage_builders.py
This PR enables library mode with audio extraction.
```python
from nv_ingest.util.pipeline.pipeline_runners import PipelineCreationSchema
config = PipelineCreationSchema(
audio_grpc_endpoint="grpc.nvcf.nvidia.com:443",
audio_function_id="<redacted>",
)
pipeline_process = start_pipeline_subprocess(config)
client = NvIngestClient(
message_client_allocator=SimpleClient,
message_client_port=7671,
message_client_hostname="localhost"
)
ingestor = (
Ingestor(client=client)
.files("/work/data/audio/*.wav")
.extract(
extract_method="audio",
)
)
```
=> add library mode support to audio extraction

.github/workflows/pypi-nightly-publish.yml
Enable nv-ingest admins to manually trigger pypi publishing instead of having to wait for a nightly trigger.
=> Enable manual trigger for pypi publishing

docs/docs/index.md, docs/mkdocs.yml, docs/sphinx_docs/source/openapi.rst
Fix API docs missing from TOC, add one link, fix page title wrapper
=> Fix API docs missing from TOC, add one link, fix page title wrapper

src/nv_ingest/extraction_workflows/image/image_handlers.py
This PR proposes to remove the `document_type` suffix from the `source_name` field in the image extraction workflow, because the suffix caused confusion for some customers. This aligns with other extraction workflows (the only exception is PDF extraction, where including `document_type` in `source_name` is intentional due to the way PDF metadata is processed).
=> remove document_type suffix from source_name in image data extraction

client/src/nv_ingest_client/client/client.py, client/src/nv_ingest_client/client/interface.py, client/src/nv_ingest_client/util/processing.py, tests/nv_ingest_client/client/test_interface.py
```python
results = ingestor.ingest()  # Existing behavior
results, failures = ingestor.ingest(return_failures=True)  # New behavior
```
=> add return failure mode to client

src/nv_ingest/modules/telemetry/otel_meter.py, src/nv_ingest/modules/telemetry/otel_tracer.py
Sometimes when a job fails, the exit timestamp is not available, and this may result in error logs being polluted irrelevant errors in opentelemetry stages. This PR proposes to use the current time as default when exit timestamps are not avilable.
```
nv-ingest-ms-runtime-1  |     latency_ms = (ts_exit - ts_entry).total_seconds() * 1e3
nv-ingest-ms-runtime-1  | TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
nv-ingest-ms-runtime-1  | Traceback (most recent call last):
nv-ingest-ms-runtime-1  |   File "/opt/conda/envs/nv_ingest_runtime/lib/python3.10/site-packages/nv_ingest/modules/telemetry/otel_tracer.py", line 115, in on_next
nv-ingest-ms-runtime-1  |     collect_timestamps(message)
nv-ingest-ms-runtime-1  |   File …
```
=> use current timestamp in telemetry when job fails

client/pyproject.toml, client/src/version.py
Adjust the `version.py` file to not attempt to use a date for an actual "release"
=> Adjust nv-ingest wheel name to be PyPi friendly

docs/docs/extraction/nv-ingest-python-api.md
One of the "note" alert boxes was broken, so I did another edit pass on the new API doc.  I also added a paragraph about Ingestor since that was one of the VDR requests.
Here is the current version live: https://docs.nvidia.com/nemo/retriever/extraction/nv-ingest-python-api/
=> A few more edits to the new API doc

src/nv_ingest/util/pipeline/pipeline_runners.py
Checking to see if this reduces the time required between re-running the local pipeline.
=> In pipeline_runners set is_port_in_use to use SO_REUSEADDR

Dockerfile
This pull request includes a change to the `Dockerfile` to reduce the image size by removing unnecessary dependencies.
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R142-R146): Removed `graphviz`, `python-graphviz`, and other dependencies to reduce the image size.
I'm not 100% sure if the test suite covers this.
=> Remove graphviz and its dependencies from Dockerfile to reduce image size

client/client_examples/examples/python_client_usage.ipynb
The notebook was using the old splitter. This PR updates it to the new, tokenizer-based splitter.
- ~~[ ] New or existing tests cover these changes.~~
- ~~[ ] If adjusting docker-compose.yaml environment variables have you ensured those are mimicked in the Helm values.yaml file.~~
=> update python client usage notebook

src/nv_ingest/util/pipeline/pipeline_runners.py
You can double-check the function ID on build: https://build.nvidia.com/nvidia/parakeet-ctc-1_1b-asr/api
=> add external parkeet endpoint for library mode

.github/workflows/conda-publish.yml, conda/build_conda_packages.sh, conda/packages/nv_ingest/meta.yaml, conda/packages/nv_ingest_api/meta.yaml, conda/packages/nv_ingest_client/meta.yaml
Adjust conda build process to accept a specific version rather than loading dev versions from scripts. This enabled making conda releases from Github
=> Adjust conda build for CI conda release support

.github/workflows/conda-publish.yml, conda/environments/nv_ingest_environment.yml, conda/packages/nv_ingest/meta.yaml
Pins the Morpheus version to 25.02
=> Pin morpheus version to 25.02

.pre-commit-config.yaml
Ignore markdown files with linter
=> Ignore markdown files for pre-commit

api/src/nv_ingest_api/internal/extract/pptx/engines/pptx_helper.py
This fixes an issue where the subtype field is blank for tables extracted from pptx documents
=> Add subtype to pptx table extraction

.pre-commit-config.yaml, README.md, docs/docs/extraction/quickstart-library-mode.md
There was a pymilvus release (2.5.6) a few days ago that is incompatible with our code and it broke library mode. This PR updates documentation to pin pymilvus to a working version.
=> Pin pymilvus version in docs

api/src/nv_ingest_api/internal/extract/image/image_helpers/common.py
Updated to return a uint8 NumPy array by removing the explicit dtype cast to float32. Applying `np.asarray` directly to a PIL image automatically produces a uint8 array, which is the expected format for downstream processing. This change avoids unnecessary type conversion and preserves the original pixel values as intended.
=> Fix image preprocessing to return uint8 array instead of float32

.github/workflows/test-library-mode.yml
This PR updates the `test-library-mode.yml` GitHub Actions workflow to explicitly install `librosa` via conda. This ensures that audio-related dependencies are available during integration tests.
=> Add librosa to test-library-mode workflow dependencies

api/api_tests/primitives/nim/model_interface/test_parakeet.py, api/src/nv_ingest_api/internal/primitives/nim/model_interface/parakeet.py, src/nv_ingest/framework/orchestration/morpheus/util/pipeline/stage_builders.py, tests/integration/conftest.py, tests/integration/test_extract_audio.py
This PR introduces an integration test for audio extraction that validates transcription output from a `.wav` file using the "audio" extract method. The test ensures that audio input is correctly processed and returns the expected transcript.
=> Add integration test for audio extraction

client/src/nv_ingest_client/util/milvus.py
This PR moves `from llama_index.embeddings.nvidia import NVIDIAEmbedding` inside the `nvingest_retrieval()` function in order to prevent top-level import from triggering logging:
```
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /opt/conda/envs/nv_ingest_runtime/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
```
and downloading when the module is not used.
=> Lazy import llama_index in milvus utility to avoid unwanted side effects

client/client_tests/client/test_interface.py, client/src/nv_ingest_client/client/interface.py
Previously, `os.path.basename(f.path)` could return incorrect results for remote paths handled by `fsspec`, particularly those including query terms in AWS pre-signed URLs https://aws-s3-presigned-url/remote.txt?a-long-query-term-with-1708-charactrers. This change uses `urllib.parse.urlparse` to extract the path component before passing it to `os.path.basename`, ensuring correct filename resolution.
=> Fix basename extraction from fsspec file URLs

client/client_tests/util/test_milvus_util.py, client/src/nv_ingest_client/util/milvus.py
This PR creates support for adding new metadata via a dataframe (pandas currently) and supplying a source field name and metadata field names. Before writing the elements to milvus all relevant user defined metadata is added to the content_metadata field as it is supplied via the dataframe. Then during search we supply the _filter kwarg which can be used to employ filtering techniques for json as defined by milvus here https://milvus.io/docs/use-json-fields.md.
=> Add milvus filter and metadata add  on support

src/nv_ingest/framework/orchestration/morpheus/util/pipeline/stage_builders.py
=> Update stage builders to convert NV_INGEST_MAX_UTIL to int from str

client/client_tests/util/test_milvus_util.py, client/src/nv_ingest_client/util/milvus.py, examples/metadata_and_filtered_search.ipynb
Adds the ability to ingest directly from a supported file. File types that are support are: json, csv, parquet. If we need another file types supported, they can be added as they are requested. Currently, all file reads are done with default settings, if we find that users require the ability to send custom values to args and kwargs we will need to add that support in.
=> Add metadata file support and example/documentation

api/src/nv_ingest_api/util/service_clients/rest/rest_client.py
This PR modifies the RestClient to allow the full URL of the nv-ingest endpoint to be passed, as an alternative to the hostname/port parameters. This is intended as a minimally intrusive, backward compatible change that can flexibly handle a variety of URL scheme, hostname, and port options. 
For example, for our application we intend to use a base URLs of the form: https://mysite.com/path. Given this base URL, the client would then be able to call https://mysite.com/path/v1/submit_job and https://mysite.com/path/v1/submit_job.
There is no way to get the current hostname/port parameters to correctly handle this type of URL, as any path after the base URL gets dropped. (It also doesn't seem to handle https:// URLs or non-default port numbers very well.) 
The PR also allows the user to …
=> Provide option to pass full url and headers to RestClient

helm/values.yaml
Set NIM_TRITON_MODEL_BATCH_SIZE = 1 for all NIMs by default. Values can be overridden at deploy time by using `--set {NIM_NAME}.env.NIM_TRITON_MODEL_BATCH_SIZE=X`
- [] New or existing tests cover these changes.
=> Set NIM_TRITON_MODEL_BATCH_SIZE = 1 for all NIMs by default

docker-compose.yaml
This PR introduces a default on `NV_INGEST_MAX_UTIL` to prevent overload on machines with a large number of cores.
=> Set default NV_INGEST_MAX_UTIL in docker compose

.github/workflows/pypi-nightly-publish.yml
Adjust Github PyPi workflow to publish from main
=> Adjust Github PyPi workflow to publish from main

helm/templates/secrets.yaml
Move to using `stringData` instead of `data` entries for k8s secrets.
=> Move to using stringData in secrets instead of data

.github/workflows/pypi-nightly-publish.yml
Adjust nightly pypi to be built from "main" branch
=> Adjust nightly pypi to be built from "main" branch

api/src/nv_ingest_api/internal/transform/embed_text.py, api/src/nv_ingest_api/util/converters/type_mappings.py, client/src/nv_ingest_client/primitives/tasks/extract.py
Same workaround for HTML as in https://github.com/NVIDIA/nv-ingest/pull/678 to unblock downstream teams until we have a more robust interface.
=> Allow specifying extract_method on html types

helm/Chart.lock, helm/Chart.yaml, helm/README.md, helm/values.yaml
Add Nvidia riva-asr helm chart as optional deployment
=> Add Nvidia riva-asr helm chart as optional deployment

api/api_tests/primitives/nim/test_nim_client.py, api/src/nv_ingest_api/internal/primitives/nim/nim_client.py
This PR provides a unit test for grpc, where if you have only one output, it is expected that the output is not in a list otherwise it should be a list.
=> Add test for NIM client single vs multiple response grpc

README.md, docs/docs/extraction/overview.md
Update readme intro to use docs intro with full name
Duplicate changes from #747 (main) into release/25.4.2
=> Update readme intro to use docs intro with full name

api/src/nv_ingest_api/internal/primitives/nim/model_interface/custom_ocr.py
=> guard against error string responses in custom ocr extractor

.github/workflows/test-library-mode.yml, README.md, api/api_tests/internal/extract/html/__init__.py, api/api_tests/internal/extract/html/test_html_extractor.py, api/src/nv_ingest_api/internal/extract/html/__init__.py, api/src/nv_ingest_api/internal/extract/html/html_extractor.py, api/src/nv_ingest_api/internal/schemas/extract/extract_html_schema.py, client/src/nv_ingest_client/primitives/tasks/extract.py, conda/environments/nv_ingest_environment.yml, conda/packages/nv_ingest/meta.yaml, src/nv_ingest/framework/orchestration/ray/stages/extractors/html_extractor.py, src/nv_ingest/framework/orchestration/ray/util/pipeline/pipeline_builders.py, src/nv_ingest/framework/orchestration/ray/util/pipeline/stage_builders.py, src/pyproject.toml
This adds an HTML extractor stage that uses [markitdown](https://github.com/microsoft/markitdown) to convert the raw html to markdown
=> Add HTML extractor stage

api/api_tests/interface/test_interface.py, api/api_tests/internal/schemas/transform/test_image_caption_schema.py, api/api_tests/internal/transform/test_caption_image.py, api/src/nv_ingest_api/interface/transform.py, api/src/nv_ingest_api/internal/schemas/meta/ingest_job_schema.py, api/src/nv_ingest_api/internal/schemas/transform/transform_image_caption_schema.py, api/src/nv_ingest_api/internal/transform/caption_image.py, src/nv_ingest/framework/orchestration/ray/examples/pipeline_test_harness.py, src/nv_ingest/framework/orchestration/ray/util/pipeline/stage_builders.py, tests/service_tests/schemas/test_image_caption_extraction_schema.py
=> Revert 'caption_model_name' to 'model_name' for backwards compatibility.

client/client_tests/util/test_milvus_util.py, client/src/nv_ingest_client/util/vdb/milvus.py
This PR fixes a bug where if a chunk has text length larger than allowed by milvus, it produces a warning but if that chunk does not have the necessary fields, a keyError is raised. This will not happen now.
=> fix logging error when page number not available

api/api_tests/internal/transform/test_split_text.py, api/src/nv_ingest_api/internal/transform/split_text.py
This adds support for using the SplitTask with the `"split_source_types":` `"mp3"` or `"wav"`
=> Add SplitTask support for audio file types

api/src/nv_ingest_api/internal/transform/embed_text.py, src/nv_ingest/framework/orchestration/ray/stages/transforms/text_embed.py, src/nv_ingest/framework/orchestration/ray/util/pipeline/pipeline_builders.py
Fixes a regression where the image captioning stage came later in the pipeline than the embedding stage. Resulting in failures to create embeddings for captioned images.
=> Fix caption embedding ordering

.github/workflows/pypi-nightly-publish.yml
Adjust pypi version to use YYYY instead of YY in nightly package names
=> Adjust pypi version to use YYYY instead of YY in nightly package names

api/api_tests/internal/primitives/nim/model_interface/test_yolox_interface_base.py, api/api_tests/util/image_processing/test_transforms.py, api/src/nv_ingest_api/internal/extract/pdf/engines/nemoretriever.py, api/src/nv_ingest_api/internal/extract/pdf/engines/pdfium.py, api/src/nv_ingest_api/internal/primitives/nim/model_interface/nemoretriever_parse.py, api/src/nv_ingest_api/internal/primitives/nim/model_interface/yolox.py, api/src/nv_ingest_api/util/image_processing/transforms.py, api/src/nv_ingest_api/util/pdf/pdfium.py
This PR improves image processing across the application by introducing support for configurable image formats (JPEG/PNG), replacing PIL with OpenCV for faster encoding/decoding, and expanding test coverage.
- **JPEG Format Support**  
Introduced `YOLOX_PAGE_IMAGE_FORMAT` as an environment variable to control image output format. Default is PNG; JPEG can now be used for performance optimization.
- **OpenCV Optimization**  
Replaced PIL with OpenCV in image encoding/decoding to improve speed, reduce memory usage, and ensure thread safety.
- **Why JPEG?**  
Benchmarks across 100 runs on a single CPU thread using `example_combined.jpg` (1187×1536) show that JPEG encoding with OpenCV offers a ~17x speedup over PNG with Pillow, along with smaller output sizes and faster decoding. …
=> [REVIEW] Add Image Processing with JPEG Support and OpenCV Optimizations

client/src/nv_ingest_client/util/vdb/milvus.py
This restores backward compatibility. Without this change, I get errors such as:
```python
Traceback (most recent call last):
File "/work/git/nv-ingest/bo767_full.py", line 142, in <module>
hits = get_recall_scores(df_query, "multimodal")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/work/git/nv-ingest/bo767_full.py", line 112, in get_recall_scores
retrieved_pages = [str(result['entity']['content_metadata']['page_number']) for result in retrieved_answers]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'page_number'
```
=> Fix content metadata filtering in client vdb upload

client/src/nv_ingest_client/util/vdb/milvus.py
Fix the search speed of milvus while still guaranteeing ingest to milvus is complete.
=> Mil search speed

client/src/nv_ingest_client/client/interface.py
This PR fixes a recently introduced bug where `Ingestor.save_to_disk(output_directory=...)` would write result .jsonl files to the current working directory instead of the specified output_directory.
=> Fix incorrect path when saving results to disk

api/src/nv_ingest_api/internal/schemas/transform/transform_image_caption_schema.py, client/src/nv_ingest_client/nv_ingest_cli.py, docs/docs/extraction/nv-ingest-python-api.md, helm/README.md, helm/values.yaml, src/nv_ingest/framework/orchestration/ray/util/pipeline/pipeline_runners.py, tests/service_tests/schemas/test_image_caption_extraction_schema.py
Update VLM caption endpoint url with the correct url.
https://build.nvidia.com/nvidia/llama-3.1-nemotron-nano-vl-8b-v1?snippet_tab=Python
=> Fix vlm build endpoint url

client/src/nv_ingest_client/client/client.py
=> Adding the option to set an env var for client batch size

client/src/nv_ingest_client/util/transport.py
This fixes an issue where using the `infer_microservice` function in transport.py with an http embedding endpoint still results in an attempted grpc call to the endpoint
=> Fix issue with embed calls from client

client/src/nv_ingest_client/util/vdb/milvus.py
Previously the vdb_upload task would ignore the threshold parameter. This fixes that issue
=> Fix threshold parameter in vdb_upload

README.md, docs/docs/extraction/audio.md, docs/docs/extraction/data-store.md, docs/docs/extraction/nemoretriever-parse.md, docs/docs/extraction/nv-ingest-python-api.md, docs/docs/extraction/overview.md, docs/docs/extraction/quickstart-guide.md, docs/docs/extraction/quickstart-library-mode.md, docs/docs/extraction/releasenotes-nv-ingest.md, docs/docs/extraction/support-matrix.md, docs/docs/extraction/vlm-embed.md, docs/docs/index.md
docs: Updates including return_failures edit, Overview addition, html(markdown), and 400 MB Relnote 
Same changes as #952 cherry-picked into 25.9.0-RC1
=> docs: Updates including return_failures edit, Overview addition, html(markdown), and 400 MB Relnote (25.9.0-RC1)

docs/docs/extraction/audio.md, docs/docs/extraction/nemoretriever-parse.md, docs/docs/extraction/nv-ingest-python-api.md, docs/docs/extraction/troubleshoot.md
Remove --build and edit OOM / save to disk content (25.9.0-RC2)
(cherry picked from commit 9702c97ae52f4d5b5b524d78a9c1e9d0d8c90a16)
Includes edit for #975
=> docs: Remove --build and edit OOM / save to disk content (25.9.0-RC2)

.pre-commit-config.yaml, api/uv.lock, client/uv.lock, src/uv.lock
Add UV lock files for each package for scanning tools
=> Add UV lock files for each package for scanning tools

client/src/nv_ingest_client/util/vdb/milvus.py
This PR solves a bug that was introduced in the new milvus streaming insert logic. Where if the user does not insert enough rows to start the flush process, all rows are kept in a growing segment that is never sealed. This causes the index row count to not grow and kept us in a loop when checking for updates index row count.
=> add flush streaming inserts

api/api_tests/internal/primitives/nim/model_interface/test_vlm.py, api/src/nv_ingest_api/internal/primitives/nim/model_interface/vlm.py
Change prompt in vlm.py to send Image as a image_url type, not include as a string with prompt.
Feature request: https://github.com/NVIDIA/nv-ingest/issues/1030
=> update prompt for VLM inference requests.

.github/workflows/docker-nightly-publish.yml, .github/workflows/docker-release-publish.yml
Using `--load` in https://github.com/NVIDIA/nv-ingest/pull/1081 results in an error:
```
ERROR: failed to build: docker exporter does not currently support exporting manifest lists
```
`--load` is for single platforms. `--push` should be used on multi-platform.
=> [ci] push docker image directly from buildx step
