NVIDIA/nv-ingest

- .github/ISSUE_TEMPLATE/bug_report_form.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_request_correction.yml
- .github/ISSUE_TEMPLATE/documentation_request_new.yml
- .github/ISSUE_TEMPLATE/feature_request_form.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds issue and PR templates for NV-Ingest.
> Add issue and PR templates

- README.md
- docker-compose.yaml
- src/nv_ingest/modules/filters/image_filter.py
- src/nv_ingest/stages/filters/image_filter.py
> Remove references to internal Nvidia Gitlab instance

- examples/langchain_multimodal_rag.ipynb
- examples/llama_index_multimodal_rag.ipynb
> Add Langchain and LLama Index RAG example notebooks

- client/src/nv_ingest_client/client/client.py
- client/src/nv_ingest_client/message_clients/redis/redis_client.py
- src/nv_ingest/modules/sinks/redis_task_sink.py
- tests/nv_ingest_client/redis/test_redis_client.py
> Resolves #65 -- Add support for multi-part response messages from Redis client to support results > 256 MB

- src/nv_ingest/util/image_processing/table_and_chart.py
> Resolves #69 join_cached_and_deplot_output function is not adding all fields returned from cached.

- README.md
Removes link to the deprecated script and updates links to notebooks.
> Update links to client examples

- README.md
Closes #27.
Software requirements gathered from a clean OS installed H100 instance.
> Add hardware/software requirements to README

- helm/README.md
> Update namespace where secrets are created to nv-ingest

- README.md
This PR adds a few piece of useful info (CTK 12.2 being related to the 535 driver, bumping to Ubuntu 22.04 recommendation due to the upcoming 20.04 EOL.)
It also does a number of formatting changes to improve readability and improve the bookmark usability from GitHub.
> Update README Formatting

- .github/workflows/docker-build.yml
Provide a basic baseline for github actions CI setup. This PR should build the nv-ingest Docker image and run the Python pytests.
Further PRs will be made to expand upon these actions.
> Provide a basic baseline for github actions CI setup

- .github/workflows/docker-build.yml
- .github/workflows/docker-nightly-publish.yml
Uploads the nv-ingest container to a private registry after each CI run.
> Upload nv-ingest container

- .github/workflows/docker-nightly-publish.yml
> Adjust Github action username

- .github/workflows/docker-nightly-publish.yml
> Perform docker login after docker build step in CI action

- docker-compose.yaml
- src/pipeline.py
> Add support for 'DEFAULT' log level

- README.md
The API Generation steps are general but the developer needs keys with specific permission to pull docker resources for this repo. This PR adds detail for which team / org to use when creating the API key.
> Add EA notes for API key generation.

- docker-compose.yaml
- src/nv_ingest/stages/nim/table_extraction.py
- tests/stages/nims/test_table_extraction.py
> Update TableDataExtractor to check Paddle Version before preprocessing

- Dockerfile
> Switching away from miniconda to miniforge

- docker-compose.yaml
> Making NIM image paths and tags controllable via env vars

- .github/copy-pr-bot.yaml
Setup Nvidia copy-pr-bot to repo
> Add Nvidia copy-pr-bot to repo

- client/src/nv_ingest_client/cli/util/processing.py
- client/src/nv_ingest_client/nv_ingest_cli.py
> Add the ability to the CLI to post process returned metadata and extract image to a local media file

- README.md
> Add updated instructions for table/chart OCR extract

- client/src/nv_ingest_client/cli/util/processing.py
- client/src/nv_ingest_client/client/client.py
- client/src/nv_ingest_client/util/util.py
> Improve feedback for failed jobs through cli and client lib

- client/src/nv_ingest_client/client/client.py
- client/src/nv_ingest_client/client/interface.py
- client/src/nv_ingest_client/util/util.py
> Update ingest client so we can track job_ids to job specs

- client/setup.py
- client/src/nv_ingest_client/util/process_json_files.py
- client/src/nv_ingest_client/util/util.py
> Add helper for getting content from metadata

- src/nv_ingest/modules/telemetry/otel_tracer.py
> Make ingest traces to be nested under endpoint traces

- client/src/nv_ingest_client/client/interface.py
- client/src/nv_ingest_client/primitives/tasks/store.py
- client/src/nv_ingest_client/primitives/tasks/vdb_upload.py
- src/nv_ingest/stages/storages/embedding_storage_stage.py
- tests/nv_ingest_client/client/test_interface.py
Fixes issue with ingestor, where it does not recognize the StoreEmbedTask.
> add store_embed task to ingestor

- src/nv_ingest/extraction_workflows/docx/docxreader.py
- src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py
- src/nv_ingest/extraction_workflows/pptx/pptx_helper.py
> Update extractors to skip text primitive creation for pages if no text is extracted

- helm/README.md
- helm/values.yaml
The `VLM_CAPTION_ENDPOINT` parameter was added recently but was missing from the Helm `values.yaml` file preventing Helm from deploying successfully.
> Add vlm endpoint helm

- client/src/nv_ingest_client/util/milvus.py
The PR adds in the necessary functions to upload records to minio, bulk ingest those records into milvus and run multiple query searches, both hybrid and dense.
> add upload and search functions

- Dockerfile
> Fix bashrc to activate nv_ingest_runtime environment

- docker-compose.yaml
> Revert docker compose to point at local deplot

- client/src/nv_ingest_client/client/client.py
> Fix corner case where NvIngestClient fails to connect to REST service.

- client/requirements.txt
- client/src/nv_ingest_client/util/milvus.py
This PR makes sure that if a sparse embedding ends up with no embedding values, we add a placeholder value. Otherwise milvus will not accept the record.
> Fix sparse embedding logic

- client/requirements.txt
- client/src/nv_ingest_client/util/milvus.py
This PR changes the default dense dimension size to 2048 to support the new model. It also propagates the parameter to the top level extraction so it can be used to change the schema as the user requires.
> Prop dim param

- examples/bare_metal_example.py
- src/microservice_entrypoint.py
- src/nv_ingest/util/pipeline/pipeline_runners.py
> Update bare metal deployment to properly respect logging levels.

- deploy/pdf-blueprint.ipynb
> Remove schema from write_to_nvingest_collection function call

- src/util/image_viewer.py
> Improve image_viewer.py for general use

- docker-compose.yaml
> Update NIM versions

- docs/docs/user-guide/developer-guide/ngc-api-key.md
- docs/docs/user-guide/getting-started/quickstart-guide.md
> Fixed broken links

- examples/bare_metal_example.py
- src/nv_ingest/util/pipeline/pipeline_runners.py
> Update pipeline_runners to use smarter creation schema defaults

- client/src/nv_ingest_client/nv_ingest_cli.py
- client/src/nv_ingest_client/primitives/tasks/embed.py
- src/nv_ingest/modules/transforms/embed_extractions.py
- src/nv_ingest/schemas/ingest_job_schema.py
- src/nv_ingest/schemas/metadata_schema.py
- tests/nv_ingest/modules/sources/test_message_broker_task_source.py
- tests/nv_ingest/schemas/test_ingest_job_schema.py
- tests/nv_ingest_client/client/test_interface.py
> Enable the embedding task for all content types including image captions

- docs/docs/user-guide/developer-guide/kubernetes-dev.md
Docs: Kubernetes page: fix broken code block
> Docs: Kubernetes page: fix broken code block

- src/nv_ingest/extraction_workflows/docx/docxreader.py
> Swap build.lib import path to correct nv_ingest library

- conda/packages/nv_ingest/meta.yaml
- conda/packages/nv_ingest_client/meta.yaml
Update the Conda package build number to align with rapidsai cudf and other rapidsai projects.
> Update conda package build string and number

- conda/build_conda_packages.sh
> Add git short sha to conda package version

- conda/packages/nv_ingest/meta.yaml
- conda/packages/nv_ingest_client/meta.yaml
> Update git_sha to be used in conda build package version

- conda/packages/nv_ingest/build.sh
- conda/packages/nv_ingest_client/build.sh
> Remove conda packaging build.sh scripts

- conda/build_conda_packages.sh
- conda/packages/nv_ingest/meta.yaml
- conda/packages/nv_ingest_client/meta.yaml
> Remove duplicative date from conda package

- src/nv_ingest/modules/transforms/embed_extractions.py
> Update embed_extractions so that we no longer silently fail on embedding generation

- client/src/nv_ingest_client/util/milvus.py
This PR enables adding image captions in `["metadata"]["image_metadata"]["caption"]` to vector db.
> Add image types to ingestor vdb upload

- helm/README.md
> docs: update helm/README.md

- client/src/nv_ingest_client/nv_ingest_cli.py
- docker-compose.yaml
- src/nv_ingest/extraction_workflows/image/image_handlers.py
- src/nv_ingest/service/impl/ingest/redis_ingest_service.py
- src/nv_ingest/util/flow_control/filter_by_task.py
- src/nv_ingest/util/pipeline/stage_builders.py
> Fix regex task filtering regression and image extraction handling

- src/nv_ingest/stages/nim/chart_extraction.py
Cached doesn't require specific image dimensions, but gRPC requires all images in a batch to have the same dimensions. To work around this we revert to n calls @ batch size 1 for gRPC + cached.
> Update chart extraction stage to use single batching for gRPC cached calls

- examples/langchain_multimodal_rag.ipynb
- examples/llama_index_multimodal_rag.ipynb
> Update embedding call to get rid of warnings in LlamaIndex and Langchain multimodal notebooks

- docs/docs/user-guide/developer-guide/telemetry.md
> Fix links to missing images

- docs/docs/user-guide/index.md
Minor update to heading text.  
Some text changes to test the linter exclusion in the docs folder.
Closes #376
> Minor update and test linter exclusion

- client/src/nv_ingest_client/client/client.py
- client/src/nv_ingest_client/client/interface.py
- src/nv_ingest/modules/transforms/embed_extractions.py
- src/nv_ingest/util/pipeline/stage_builders.py
> Add simple progress bar to synchronous ingestor.ingest() call

- src/nv_ingest/util/pdf/metadata_aggregators.py
Adds missing page width to image metadata.
> Add missing page width to image metadata

- client/src/nv_ingest_client/client/client.py
> Fix incorrect return value structure from _fetch_message

- .pre-commit-config.yaml
> Adjust trailing-whitespace hook to ignore the data directory

- README.md
- deploy/pdf-blueprint.ipynb
- docs/docs/user-guide/developer-guide/environment-config.md
- docs/docs/user-guide/getting-started/prerequisites.md
- docs/docs/user-guide/getting-started/quickstart-guide.md
Remove references to ea-participants private registry.
I moved the output to text as a sample only.
> Remove references to ea-participants private registry

- .github/workflows/pypi-nightly-publish.yml
> Adjust twine dist upload path

- client/requirements.txt
- examples/langchain_multimodal_rag.ipynb
> Pin to langchain-nvidia-ai-endpoints >= 0.3.7

- src/nv_ingest/extraction_workflows/pdf/pdfium_helper.py
- src/nv_ingest/util/pdf/pdfium.py
> Experimental fix for pdf processing segfaults.

- tests/nv_ingest/util/flow_control/test_filter_by_task.py
> Fix filter by task bug

- src/nv_ingest/stages/nim/chart_extraction.py
- src/nv_ingest/stages/nim/table_extraction.py
> Fix paddle batch size specification

- src/nv_ingest/util/nim/yolox.py
In grpc mode, yolox NIMs only allow batch size in multiples of 2.
> batch in multiples of 2 for yolox nim grpc mode

- tests/import_checks.py
- tests/nv_ingest/modules/telemetry/test_otel_tracer.py
- tests/nv_ingest/stages/nims/test_chart_extraction.py
- tests/nv_ingest/stages/nims/test_table_extraction.py
- tests/nv_ingest/stages/test_image_extractor_stage.py
- tests/nv_ingest/stages/transforms/test_image_caption_extraction.py
- tests/nv_ingest/util/exception_handlers/test_decorators.py
- tests/nv_ingest/util/flow_control/test_filter_by_task.py
> Update various unit test files to be skipped if morpheus and cuda are not available

- src/nv_ingest/util/nim/paddle.py
- tests/nv_ingest/util/nim/test_cached.py
- tests/nv_ingest/util/nim/test_deplot.py
- tests/nv_ingest/util/nim/test_helpers.py
- tests/nv_ingest/util/nim/test_paddle.py
- tests/nv_ingest/util/nim/test_yolox.py
> Fix failing unit tests

- .github/workflows/pypi-nightly-publish.yml
> Only publish pypi wheel nightly

- README.md
- docs/docs/user-guide/quickstart-guide.md
Add retrieval profile to docker compose up command
> Add retrieval profile to docker compose up command

- docs/docs/user-guide/developer-guide/environment-config.md
- docs/docs/user-guide/quickstart-guide.md
> Minor doc bug fixes

- .github/workflows/build-docs.yml
- docs/sphinx_docs/source/conf.py
Enable building the sphinx docs for the `nv-ingest-api` module
> Sphinx api docs build

- .github/workflows/build-docs.yml
> Use . instead of source since github ci uses sh and not bash by default

- .github/workflows/build-docs.yml
> Activate venv to ensure mkdocs is present

- .github/workflows/build-docs.yml
> Change docs CI to vanilla Github

- .github/workflows/build-docs.yml
> Correct path to /workspace/docs/site

- docs/requirements.txt
- docs/sphinx_docs/source/conf.py
> Add nvidia-sphinx-template

- README.md
- client/src/nv_ingest_client/nv_ingest_cli.py
- docs/docs/user-guide/developer-guide/nv-ingest_cli.md
- docs/docs/user-guide/index.md
Update supported file types `docx`, `jpeg`, `pdf`, `png`, `pptx`, `svg`, `tiff`, `txt`
> Update supported file types `docx`, `jpeg`, `pdf`, `png`, `pptx`, `svg`, `tiff`, `txt`

- docker-compose.yaml
> Adding --profile vlm for self hosted VLM NIM

- client/src/nv_ingest_client/primitives/tasks/extract.py
Typo + pre-commit added in https://github.com/NVIDIA/nv-ingest/pull/483
> Fix client parameter typo added in infographics support

- docker-compose.yaml
- src/nv_ingest/util/multi_processing/mp_pool_singleton.py
> Add ability to set ingest process workers

- src/nv_ingest/util/multi_processing/mp_pool_singleton.py
- [] If adjusting docker-compose.yaml environment variables have you ensured those are mimicked in the Helm values.yaml file.
> Fix max process workers flag

- Dockerfile
- docker-compose.yaml
- docker/scripts/post_build_triggers.py
- src/nv_ingest/modules/transforms/text_splitter.py
> Make tokenizer pre-download path a configurable env variable

- docs/mkdocs.yml
Fix link from user guide to new API docs
> Fix broken link

- docs/docs/index.md
- docs/docs/user-guide/quickstart-guide.md
> Fix 2 links

- docker-compose.yaml
> Replace audio docker image with riva-asr

- client/src/nv_ingest_client/util/milvus.py
- src/nv_ingest/stages/embeddings/text_embeddings.py
- src/nv_ingest/stages/nim/audio_extraction.py
This PR adds support for text embedding extraction and vector database upload in the audio transcript extraction workflow. This enables downstream tasks to leverage embeddings for retrieval.
> enable text embedding extraction and vdb upload for audio

- .github/workflows/conda-publish.yml
> Adjust github CI to honor workflow dispatch input parameter

- src/nv_ingest/modules/telemetry/otel_tracer.py
> Fix otel trace ID by converting uuid

- docs/docs/extraction/prerequisites.md
- docs/docs/extraction/support-matrix.md
- docs/docs/index.md
- docs/mkdocs.yml
Update Retriever overview and refactor prerequisites / support matrix
> Update Retriever overview and refactor prerequisites / support matrix

- client/src/nv_ingest_client/util/milvus.py
> fix reranker output

- client/src/nv_ingest_client/util/file_processing/extract.py
- src/nv_ingest/extraction_workflows/image/image_handlers.py
- src/nv_ingest/stages/extractors/image_extractor_stage.py
> Add support for bmp files and treat html files as text

- client/src/nv_ingest_client/util/file_processing/extract.py
This updates our encoding detection to use the full file for more accurate encoding detection.
> Use full data for text encoding detection

- src/nv_ingest/stages/nim/chart_extraction.py
- src/nv_ingest/util/nim/yolox.py
> adjust image size based on yolox-graphic-elements version

- client/src/nv_ingest_client/util/milvus.py
This PR makes changes to the milvus index and increases the number of candidates used in the ranker. These changes increase the recall when using the ranker.
> this adds 1% to ranker recall

- docs/mkdocs.yml
- docs/requirements.txt
Add redirect for nemo/retriever/extraction/(index)
> Add redirect for nemo/retriever/extraction/(index)

- src/nv_ingest/util/pipeline/pipeline_runners.py
> Add a pre-launch check for libmode pipeline creation

- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/telemetry.md
> adding note for parse and updated telemetry page

- docker-compose.yaml
- src/nv_ingest/__init__.py
> suppress cuda related warnings

- client/client_examples/examples/python_client_usage.ipynb
> Update python example to llama embed model

- Dockerfile
> remove software-properties-common

- Dockerfile
- conda/environments/nv_ingest_environment.yml
- conda/packages/nv_ingest/meta.yaml
- docker-compose.yaml
- docker/scripts/entrypoint.sh
- docker/scripts/entrypoint_source_ext.sh
- src/nv_ingest/util/nim/parakeet.py
> Make librosa optional

- Dockerfile
- conda/environments/nv_ingest_environment.yml
- conda/packages/nv_ingest/meta.yaml
- conda/packages/nv_ingest_api/meta.yaml
- docker/scripts/entrypoint_source_ext.sh
- src/nv_ingest/extraction_workflows/image/image_handlers.py
- src/nv_ingest/stages/extractors/image_extractor_stage.py
- tests/nv_ingest/extraction_workflows/image/test_image_handlers.py
- tests/nv_ingest_api/primitives/test_ingest_control_message.py
> Remove use of wand/image magick

- docs/docs/extraction/environment-config.md
> update environment config documentation

- CONTRIBUTING.md
- deploy/pdf-blueprint.ipynb
- docs/docs/extraction/audio.md
- docs/docs/extraction/nemoretriever-parse.md
- docs/docs/extraction/ngc-api-key.md
- docs/docs/extraction/notebooks.md
- docs/docs/extraction/nv-ingest_cli.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/prerequisites.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/support-matrix.md
- docs/docs/extraction/telemetry.md
- docs/mkdocs.yml
VDR changes round 3, including: 
- Edit Edward's docs x 2
- Update profile information
- Fix link and fix audio profile command
- Added new Notebooks page and sprinkled links to notebooks throughout
> VDR changes round 3

- docs/mkdocs.yml
> Fix bug in TOC

- docs/docs/extraction/nv-ingest-python-api.md
> Add example of extracting text from non-standard document types

- src/nv_ingest/util/pipeline/pipeline_runners.py
> Restrict max progress engines for libmode

- README.md
- docs/docs/extraction/faq.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/mkdocs.yml
Add new FAQ page with 2 initial items
> Add new FAQ page with 2 initial items

- docs/docs/extraction/data-store.md
- docs/docs/extraction/faq.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/support-matrix.md
- docs/mkdocs.yml
Add FAQ items and create new Data page
> Add FAQ items and create new Data page

- .github/workflows/conda-publish.yml
> Output conda channel and version being built

- .github/workflows/conda-publish.yml
- conda/build_conda_packages.sh
> Display conda release version from CI

- .github/workflows/conda-publish.yml
- conda/build_conda_packages.sh
> Conda script equals

- .github/workflows/conda-publish.yml
> Replace -eq with single = for sh script of github action

- docs/docs/extraction/quickstart-library-mode.md
Add import for sys after previously adding sys for output
> Add import for sys after previously adding sys for output

- client/pyproject.toml
- conda/environments/nv_ingest_client_environment.yml
- conda/environments/nv_ingest_environment.yml
- conda/packages/nv_ingest/meta.yaml
- conda/packages/nv_ingest_api/meta.yaml
- conda/packages/nv_ingest_client/meta.yaml
> Lower requests version

- README.md
- docker-compose.yaml
- docs/docs/extraction/overview.md
- docs/docs/extraction/quickstart-library-mode.md
> Fixing docker-compose & release docs Release/25.3.0

- docker-compose.yaml
> fixing nemoretriever-parse container location & version tags

- api/src/nv_ingest_api/internal/extract/docx/engines/docxreader_helpers/docxreader.py
> Update core properties parsing for docx

- .github/workflows/test-library-mode.yml
A follow-on to https://github.com/NVIDIA/nv-ingest/pull/618.
> add missing head checkout

- .github/workflows/test-library-mode.yml
> add data and examples to test artifacts in integration test workflow

- .github/workflows/test-library-mode.yml
> run tests from artifact directory in integatrion test workflow

- api/api_tests/primitives/nim/model_interface/test_yolox_interface_page_elements.py
- api/src/nv_ingest_api/internal/primitives/nim/model_interface/yolox.py
https://github.com/NVIDIA/nv-ingest/blob/c889feb1dab2cdd1348a18e138af9b3fa052e09e/docker-compose.yaml#L12
> update default page-elements model name

- client/src/nv_ingest_client/util/milvus.py
This PR adds a helper function `get_index_types()` to support both old and new Milvus internal formats. Handles dict-based `_indexes` (pre-2.5.6) and list-based IndexParam objects (2.5.6+), enabling backward and forward compatibility when retrieving dense/sparse index types.
> extract index types from Milvus index_params

- api/src/nv_ingest_api/internal/primitives/nim/model_interface/paddle.py
This PR fixes a bug in the PaddleOCR HTTP response parsing by correctly setting and passing image dimensions for bounding box scaling. The width and height values were previously reversed; this has been corrected. The `dims` list is now also passed to postprocessing to ensure accurate bounding box scaling per image.
> Fix image dimension handling in paddle http postprocessing

- .github/workflows/test-library-mode.yml
> Fix integration test workflow to support push to main triggers

- tests/integration/conftest.py
- tests/integration/test_extract_docx.py
- tests/integration/test_extract_pptx.py
- tests/integration/utilities_for_test.py
- tests/utilities_for_test.py
This PR introduces integration tests to verify the content extraction capabilities for .docx and .pptx files
> Add integration test for docx and pptx extraction

- .devcontainer/README.md
- README.md
- client/README.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- helm/README.md
Fix casing N R Extraction --> N R extraction
Alert: this touches the readme file in the devcontainer
> Fix casing N R Extraction --> N R extraction

- api/api_tests/primitives/nim/model_interface/test_helpers.py
- api/src/nv_ingest_api/internal/primitives/nim/model_interface/helpers.py
- api/src/nv_ingest_api/internal/primitives/nim/model_interface/yolox.py
Follow up to https://github.com/NVIDIA/nv-ingest/pull/628.
> Fix model name query for nvcf

- README.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/quickstart-library-mode.md
Edit pass on Readme and Library Mode Quickstart
> Edit pass on Readme and Library Mode Quickstart

- docs/docs/extraction/quickstart-guide.md
Fix typo and add ulimit troubleshooting (main)
> Fix typo and add ulimit troubleshooting (main)

- docs/docs/extraction/quickstart-guide.md
Fix typo and add ulimit troubleshooting (25.3.0)
> Fix typo and add ulimit troubleshooting (25.3.0)

- src/nv_ingest/framework/orchestration/morpheus/util/pipeline/stage_builders.py
> Fix MAX_UTIL cast to int 

- client/src/nv_ingest_client/util/milvus.py
This PR changes current informational logs for using the error code to info, which more accurately fits the messages displayed.
> Milvus log fix

- helm/values.yaml
> Set triton max batch size for llama 3.2 embed model

- docs/docs/extraction/helm.md
- docs/docs/extraction/notebooks.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/prerequisites.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/support-matrix.md
- docs/mkdocs.yml
Update titles and links for 3 deployment pages - suggested by @jdye64
> Update titles and links for 3 deployment pages

- docs/overrides/main.html
> Add Adobe Analytics scripts

- docs/docs/extraction/quickstart-guide.md
Update ulimit troubleshooting section
> Update ulimit troubleshooting section

- .github/workflows/build-docs.yml
- .github/workflows/conda-publish.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-nightly-publish.yml
- .github/workflows/pre-commit.yml
Update workflows on main to specifically use main branch:
> Update workflows on main to specifically use main branch:

- client/src/nv_ingest_client/primitives/tasks/extract.py
> Add txt document types to extract method map

- api/api_tests/util/converters/test_type_mappings.py
Fix unit test failure in #682. (But how did the CI pass in #682?)
> Fix html content type unit test

- api/api_tests/util/converters/test_type_mappings.py
- api/src/nv_ingest_api/internal/transform/embed_text.py
- api/src/nv_ingest_api/util/converters/type_mappings.py
- client/src/nv_ingest_client/primitives/tasks/extract.py
Same as #682 to the release branch.
> Allow specifying extract_method on html types (#682)

- client/src/nv_ingest_client/client/interface.py
> Improve `glob`  specification handling in Ingestor `.files` method.

- docs/docs/extraction/chunking.md
- docs/docs/extraction/nv-ingest-python-api.md
- docs/mkdocs.yml
@ChrisJar 's expanded documentation for chunking/splitting, with my edit / reorg added.
This replaces #676
> Add expanded documentation for chunking/splitting WITH EDIT

- client/src/nv_ingest_client/client/interface.py
Bug fix -- removes incorrect labeling of remote files with glob wild-cards as optional local files
> Removes incorrect labeling of remote files with glob wild-cards as optional local files

- conda/environments/nv_ingest_environment.yml
> pin h11 pkg version to address critical CVE

- api/src/nv_ingest_api/internal/transform/embed_text.py
- client/client_tests/primitives/tasks/test_embed.py
- client/src/nv_ingest_client/primitives/tasks/embed.py
> Re-enable embed task params

- README.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/telemetry.md
Release notes for 25.04 and fix file types
> Release notes for 25.04 and fix file types

- docs/docs/extraction/releasenotes-nv-ingest.md
docs: Update Release Notes formatting only
> docs: Update Release Notes formatting

- README.md
- client/client_tests/util/test_milvus_util.py
- client/pyproject.toml
- client/src/nv_ingest_client/util/milvus.py
- docker-compose.yaml
- docs/docs/extraction/quickstart-library-mode.md
- helm/Chart.lock
- helm/Chart.yaml
- helm/README.md
- helm/README.md.gotmpl
- helm/mig/nv-ingest-mig-config.yaml
- helm/values.yaml
- src/nv_ingest/api/main.py
> 25.4.2 release prep

- .github/workflows/pypi-nightly-publish.yml
> Adjust nightly pypi workflow to allow for specifying a source branch

- .github/workflows/pypi-nightly-publish.yml
> Use proper syntax for env variable in github workflow

- .github/workflows/pypi-nightly-publish.yml
> Adjust to have release type and version

- api/src/version.py
> Only manually check for pep compliance if it isn't a release

- README.md
- docs/docs/extraction/quickstart-library-mode.md
> Update library mode example snippets for Release/25.4.2

- client/src/nv_ingest_client/client/client.py
> Fixes Ingestor regression where task failures we're not being returned corretly

- .github/workflows/docker-build.yml
> default to PR merge branch for run

- api/api_tests/internal/extract/docx/test_docx_extractor.py
- api/src/nv_ingest_api/internal/extract/audio/audio_extraction.py
- api/src/nv_ingest_api/internal/extract/docx/docx_extractor.py
- api/src/nv_ingest_api/internal/extract/image/image_extractor.py
- api/src/nv_ingest_api/internal/extract/pptx/engines/pptx_helper.py
- api/src/nv_ingest_api/internal/extract/pptx/pptx_extractor.py
- api/src/nv_ingest_api/internal/transform/embed_text.py
- docker-compose.yaml
- examples/launch_libmode_and_run_ingestor.py
- examples/launch_libmode_service.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/audio_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/docx_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/pdf_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/pptx_extractor.py
- src/nv_ingest/framework/orchestration/ray/util/pipeline/pipeline_runners.py
- tests/integration/conftest.py
> Fix multi-modal parsing for docx, pptx, image, and audio. Unified config improvements.

- .github/workflows/test-library-mode.yml
> bump runner image for libmode test

- .github/workflows/test-library-mode.yml
> Link conda libraries in libmode integration test

- .github/workflows/test-library-mode.yml
> downgrade to cuda 12.2

- .github/workflows/test-library-mode.yml
This reverts commit 0d78544cb8d2d4dfeb0f9a4c6deaf74b7803df99.
> Revert "downgrade to cuda 12.2 (#742)"

- api/src/nv_ingest_api/internal/extract/image/chart_extractor.py
- api/src/nv_ingest_api/internal/extract/image/image_helpers/common.py
- api/src/nv_ingest_api/internal/extract/image/infographic_extractor.py
- api/src/nv_ingest_api/internal/extract/image/table_extractor.py
- api/src/nv_ingest_api/internal/extract/pdf/engines/nemoretriever.py
- api/src/nv_ingest_api/internal/extract/pdf/engines/pdfium.py
- api/src/nv_ingest_api/util/image_processing/processing.py
- api/src/nv_ingest_api/util/pdf/pdfium.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/chart_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/infographic_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/pdf_extractor.py
- src/nv_ingest/framework/orchestration/ray/stages/extractors/table_extractor.py
This PR restores tracing of subtasks in the extraction tasks.
> fix tracing for extraction subtasks

- docs/docs/extraction/quickstart-library-mode.md
Update library mode page code to use 25.4.2
> Update library mode page code to use 25.4.2

- custom_ocr/Dockerfile
- custom_ocr/start_server.py
- docker-compose.yaml
> add customocr dockerfile and server script

- api/api_tests/internal/extract/image/test_chart_extractor.py
- api/api_tests/internal/primitives/nim/model_interface/test_custom_ocr.py
- api/api_tests/internal/schemas/extract/test_extract_chart_schema.py
- api/api_tests/internal/schemas/extract/test_extract_infographic_schema.py
- api/api_tests/internal/schemas/extract/test_extract_table_schema.py
- api/src/nv_ingest_api/internal/extract/pdf/engines/pdfium.py
- custom_ocr/start_server.py
- src/nv_ingest/framework/orchestration/ray/util/pipeline/pipeline_runners.py
- tests/service_tests/schemas/test_chart_extractor_schema.py
- tests/service_tests/schemas/test_table_extractor_schema.py
> [performance] Fix table output format and make markdown default

- docker-compose.yaml
> move ocr container to first gpu

- README.md
- docs/docs/extraction/overview.md
Update readme intro to use docs intro with full name
> Update readme intro to use docs intro with full name

- api/src/nv_ingest_api/internal/extract/pptx/engines/pptx_helper.py
- api/src/nv_ingest_api/internal/transform/split_text.py
- docker-compose.yaml
> Allow pptx processing to fail for specific sub-elements without failing the entire document.

- src/nv_ingest/framework/orchestration/ray/primitives/ray_pipeline.py
- src/nv_ingest/framework/orchestration/ray/primitives/ray_stat_collector.py
> Improve shutdown behavior of RayPipeline

- docs/docs/extraction/nemoretriever-parse.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/support-matrix.md
- docs/docs/extraction/troubleshoot.md
- docs/docs/overview.md
- docs/mkdocs.yml
Miscellaneous bug fixes and improvements including:
- Update support matrix page / quickstart page profile information section to clarify core / advanced features and requirements
- Add new troubleshooting page with 2 existing items moved from other page and 2 new items
> docs: Miscellaneous bug fixes and improvements

- client/pyproject.toml
- src/pyproject.toml
Bump pymilvus version to 2.5.10
> Bump pymilvus version to 2.5.10

- helm/Chart.lock
- helm/README.md
- helm/values.yaml
Update Zipkin JAVA_OPTS so that Zipkin has more memory on startup
> Update Zipkin JAVA_OPTS so that Zipkin has more memory on startup

- .github/workflows/test-library-mode.yml
> install markitdown in library mode integration test

- helm/README.md
- helm/README.md.gotmpl
Update Helm readme to clarify upgrade procedure
> Update Helm readme to clarify upgrade procedure

- docs/docs/extraction/notebooks.md
Add new notebooks to notebook page
> Add new notebooks to notebook page

- docs/docs/extraction/custom-metadata.md
- docs/mkdocs.yml
Add new custom metadata page
First draft attempt!
> Add new custom metadata page

- .github/workflows/docker-build.yml
- .github/workflows/docker-nightly-publish.yml
- .github/workflows/docker-release-publish.yml
Perform NGC docker login to pull nvcr.io private ubuntu image
> Perform NGC docker login to pull nvcr.io private ubuntu image

- .github/workflows/test-library-mode.yml
> pip install torch in ci library mode

- .github/workflows/test-library-mode.yml
This reverts commit eb100138a5188c3dbf8461adcf99c4dc51d4066b.
> Revert "pip install torch in ci library mode (#824)"

- helm/README.md
- helm/README.md.gotmpl
- helm/mig/nv-ingest-mig-values.yaml
> Add doc section about adjust MIG k8s request/limit values

- README.md
- docs/docs/extraction/helm.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/releasenotes-nv-ingest.md
docs: Update 25.6.1-->25.6.2
This also needs to go into release/25.6.2 after the branch is ready.
> docs: Update 25.6.1-->25.6.2

- docs/docs/extraction/user-defined-stages.md
- docs/mkdocs.yml
Devin's user-defined stage doc plus edit pass
> docs: Devin's user-defined stage doc plus edit pass

- .github/workflows/pypi-nightly-publish.yml
- api/src/version.py
- client/src/version.py
- src/nv_ingest/version.py
Remove pep validation as other components now take care of that logicELOG. -->
> Remove pep validation as other components now take care of that logic

- .github/workflows/test-library-mode.yml
> pin riva client in library mode test

- docs/docs/index.md
- docs/mkdocs.yml
- docs/overrides/main.html
- docs/requirements.txt
This commit contains changes to enable versioning for the documentation.  
This doesn't create or publish the versioning yet.
> docs: Enable versioning

- client/src/nv_ingest_client/client/interface.py
- client/src/nv_ingest_client/util/vdb/__init__.py
- client/src/nv_ingest_client/util/vdb/milvus.py
This PR fixes issues with some of the integration tests, it introduces logic to turn on and off nullable option for fields.
> milvus on/off nullable field

- docker-compose.yaml
Reverting env var change that was specific to https://github.com/nvidia/nv-ingest/pull/793.
> fix docker compose env var for embedder

- docs/docs/extraction/releasenotes-nv-ingest.md
Add release notes for 25.6.3 (25.6.3)
> docs: Add release notes for 25.6.3 (25.6.3)

- docs/docs/extraction/releasenotes-nv-ingest.md
Add release notes for 25.6.3 (main)
> docs: Add release notes for 25.6.3 (main)

- docs/docs/index.md
- docs/mkdocs.yml
- docs/requirements.txt
> Nkm/fix 25.6.3 versioning

- helm/values.yaml
Bump Redis container version to 7.4.3
> Bump Redis container version to 7.4.3

- docs/docs/extraction/audio.md
- docs/docs/extraction/data-store.md
- docs/docs/extraction/notebooks.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- examples/building_vdb_operator.ipynb
Updates for the 25.07 launch (QA Draft)
> docs: Updates for the 25.07 launch (QA Draft) 

- client/client_tests/primitives/jobs/test_job_spec.py
- client/src/nv_ingest_client/client/interface.py
- client/src/nv_ingest_client/primitives/jobs/job_spec.py
- client/src/nv_ingest_client/util/util.py
This PR adds stable ordering  of input files , (still testing/opening early for feedback)
> [REVIEW] Add stable ordering based on file sizes

- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/support-matrix.md
- helm/README.md
Update 25.07 release notes, support matrix, and more ocr updates
> docs: Update 25.07 release notes, support matrix, and more ocr updates

- Dockerfile
- Dockerfile-Ray
- conda/environments/nv_ingest_environment.yml
- docker-compose.yaml
Updating Ray Wheel Env per Anyscale
> Updating Ray Wheel Env per Anyscale

- src/nv_ingest/framework/orchestration/ray/util/pipeline/stage_builders.py
> Experimental 25 6 4 rc3 replica clamp

- api/src/nv_ingest_api/internal/transform/embed_text.py
> Remove experimental page image code to fix empty image content

- examples/llama_index_multimodal_rag.ipynb
- examples/reindex_example.ipynb
Small fixes to our example notebooks
> Update example notebooks

- docs/docs/extraction/audio.md
- docs/docs/extraction/data-store.md
- docs/docs/extraction/nemoretriever-parse.md
- docs/docs/extraction/vlm-embed.md
- docs/mkdocs.yml
Edit pass on new VLM / Multimodal page and related changes.
@edknv , Looked really good.  Just a few wording changes and minor structural changes.
Related to #943
> docs: Edit pass on new VLM / Multimodal page and related changes

- docs/docs/extraction/chunking.md
This fixes a small issue with the documentation concerning the split task.
> Fix split docs

- examples/llama_index_multimodal_rag.ipynb
> Fix typo in llama notebook

- scripts/interact/ingest_documents.py
- scripts/interact/utils.py
Introduce utility for ingesting documents
> Introduce utility for ingesting documents

- README.md
- docs/docs/extraction/audio.md
- docs/docs/extraction/data-store.md
- docs/docs/extraction/nemoretriever-parse.md
- docs/docs/extraction/nv-ingest-python-api.md
- docs/docs/extraction/overview.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/extraction/releasenotes-nv-ingest.md
- docs/docs/extraction/vlm-embed.md
- docs/docs/index.md
Updates including return_failures edit, Overview addition, html(markdown), and 400 MB Relnote
> docs: Updates including return_failures edit, Overview addition, html(markdown), and 400 MB Relnote

- tests/integration/conftest.py
> Fix pipeline config path in integration test

- docker-compose.yaml
- src/nv_ingest/framework/orchestration/process/dependent_services.py
- src/nv_ingest/framework/orchestration/process/execution.py
- src/nv_ingest/framework/orchestration/process/lifecycle.py
- src/nv_ingest/framework/orchestration/process/strategies.py
- src/nv_ingest/framework/orchestration/process/termination.py
- src/nv_ingest/framework/orchestration/ray/primitives/ray_pipeline.py
- tests/integration/test_examples.py
- tests/integration/test_extract_docx.py
- tests/integration/test_extract_pdf.py
> [Draft] fixing integration tests

- tests/integration/conftest.py
- tests/integration/test_extract_docx.py
- tests/integration/test_extract_images.py
- tests/integration/test_extract_pdf.py
- tests/integration/test_extract_pptx.py
- tests/integration/utilities_for_test.py
- tests/service_tests/pipeline/test_pipeline_build_default_pipeline.py
- tests/utilities_for_test.py
> Testing fixes for remaining CI failure.

- client/client_examples/examples/cli_client_usage.ipynb
> Fix port and host in cli notebook

- rtx/config/otel-collector-config.yaml
- rtx/config/prometheus.yaml
- rtx/docs/quickstart-guide.md
- rtx/podman-compose.yaml
- create a separate folder for podman deployment
- apply rtx specific optimizations to containers including limiting of threads
- updated docs
> Enable podman deployment

- docs/sphinx_docs/source/index.rst
> Add basic usage overview to api reference

- docs/docs/extraction/audio.md
- docs/docs/extraction/nemoretriever-parse.md
- docs/docs/extraction/nv-ingest-python-api.md
- docs/docs/extraction/troubleshoot.md
Remove --build and edit OOM / save to disk content (main)
Includes edit for #975
> docs: Remove --build and edit OOM / save to disk content (main)

- docs/docs/extraction/releasenotes-nv-ingest.md
Fix helm link in release notes
> docs: Fix helm link in release notes

- README.md
- docs/docs/extraction/quickstart-guide.md
- docs/docs/extraction/quickstart-library-mode.md
- docs/docs/index.md
Add RAG Blueprint to applications section and Update install versions (main)
> Add RAG Blueprint to applications section and Update install versions (main)

- docs/docs/extraction/quickstart-guide.md
- helm/README.md
> Update nr ocr model name to scene_text_ensemble in docs

- README.md
- docs/docs/extraction/quickstart-library-mode.md
> Add milvus-lite install to library mode quickstart

- api/api_tests/util/dataloader/dataloader_test_tools.py
- docker/scripts/install_ffmpeg.sh
> Remove libopenh264

- docker-compose.yaml
- helm/values.yaml
Update `nvcr.io/nvidia/nemo-microservices/nv-ingest` to use latest when developing.
> Update Base Image Version

- .github/workflows/docker-nightly-publish.yml
- .github/workflows/docker-release-publish.yml
Follow-up to https://github.com/NVIDIA/nv-ingest/pull/1069
> Add missing arg in docker publish ci workflow
